#!/usr/bin/env ruby

file = $*[0]

`git symbolic-ref HEAD` =~ /^refs\/heads\/(\d*)_/
if $1
  File.open(file, 'r+') do |io|
    content = io.lines.to_a
    msg = content.first.chomp
    if msg.empty?
      io.rewind
      io.puts "[\##$1] "
      io.puts content
    end
  end
end
